export interface AgentGamePrincipal { runtimeAgentId: string; backendAgentId: string; }
export interface RegisteredAvatarIdentity { avatarIdentityId: string; avatarAssetDigest: string; sourceType: "upstream"; sourceSystem: "milaidy"; assetType: "vrm"; assetRef: string; fallbackAllowed: false; }
export interface RuntimeAgentRegistration { backendAgentId: string; runtimeAgentId: string; avatarIdentity: RegisteredAvatarIdentity; registrationRevision: number; registrationDigest: string; }
export interface GameRunBinding { bindingId: string; operationBindingId: string; operationId: string; operationIntentDigest: string; coordinatorGeneration: number; operationProfileDigest: string; runClass: "certification" | "non_certified_rehearsal"; certificationEligible: boolean; principal: AgentGamePrincipal; conversationId?: string; streamSessionId: string; gameRunId: string; gameId: string; sourceId?: string; sourceCapabilityDigest?: string; controlMode: "fenced_agent_v1"; avatarIdentity: RegisteredAvatarIdentity; createdAtAuthorityMs: number; }
export type SourceFreeGameRunBinding = GameRunBinding & { sourceId?: never; sourceCapabilityDigest?: never; };
export type BoundGameRunBinding = GameRunBinding & { sourceId: string; sourceCapabilityDigest: string; };
export interface GameplayRuntimeProvenance { bridgeId: string; bridgeVersion: string; bridgeDigest: string; adapterManifestDigest: string; adapterVersion: string; gameAssetDigest: string; runtimeProvenanceDigest: string; }
export interface ControllerArtifactManifest { schemaVersion: "gameplay-controller-artifact.v1"; packageName: string; controllerId: string; controllerVersion: string; entrypoint: string; files: Array<{ path: string; sha256: string }>; artifactDigest: string; }
export interface GameCertificationCandidatePin { schemaVersion: "gameplay-certification-candidate.v1"; gameId: string; bridgeVersion: string; bridgeDigest: string; adapterVersion: string; adapterManifestDigest: string; controllerVersion: string; controllerDigest: string; observationSchemaVersion: string; eventSchemaVersion: string; progressSchemaVersion: string; controlSchemaVersion: string; sourceAnchorDigest: string; initialFixtureDigest: string; environment: "local-composition"; candidateDigest: string; }
export interface AgentGameplayExecutionProvenance { controllerId: string; controllerVersion: string; controllerDigest: string; gameplayPolicyId: string; gameplayPolicyVersion: number; gameplayPolicyDigest: string; directiveId: string; directiveDigest: string; executionProvenanceDigest: string; }
export interface GameplayEvidenceWindowContext { binding: BoundGameRunBinding; runtime: GameplayRuntimeProvenance; execution: AgentGameplayExecutionProvenance; certificationCandidateDigest: string; contextDigest: string; }
export type GameControlOwnerType = "agent" | "certification_harness";
export interface GameControlLease { leaseId: string; gameRunId: string; ownerType: GameControlOwnerType; fence: number; acquiredAtAuthorityMs: number; expiresAtAuthorityMs: number; renewalIntervalMs: number; state: "active" | "revocation_requested" | "revoked" | "expired"; }
export interface GameAdapterManifest { gameId: string; adapterVersion: string; observationSchemaVersion: string; eventSchemaVersion: string; progressSchemaVersion: string; controlSchemaVersion: string; controllerFamilies: string[]; supportedLifecycleCommands: Array<"start" | "pause" | "resume" | "restart">; observations: { stateSchemaId: string; featureIds: string[]; appliedControls: boolean; minimumHz: number; maximumGapMs: number; }; controls: { descriptors: GameControlDescriptor[]; commandSemantics: "complete_snapshot" | "partial_events"; maximumIntentAgeMs: number; maximumHoldMs: number; maximumSilenceMs: number; }; evidence: { stateProgression: boolean; visualProgression: boolean; deterministicReplay: boolean; }; }
export type GameControlDescriptor = { id: string; kind: "digital"; supportsHold: boolean; neutral: false; } | { id: string; kind: "analog"; minimum: number; maximum: number; neutral: number; } | { id: string; kind: "pointer"; coordinateSpace: "game-normalized"; buttons: Array<"primary" | "secondary" | "middle">; supportsMove: boolean; supportsHold: boolean; };
export interface GameCertificationRecord { gameId: string; bridgeVersion: string; bridgeDigest: string; adapterVersion: string; adapterManifestDigest: string; controllerVersion: string; controllerDigest: string; observationSchemaVersion: string; eventSchemaVersion: string; progressSchemaVersion: string; controlSchemaVersion: string; sourceAnchorDigest: string; gameAssetDigest: string; environment: "simulated" | "local-runtime" | "local-composition" | "hosted"; level: "contract-complete" | "simulated" | "local-runtime" | "local-composition" | "hosted-runtime" | "production-approved"; evidencePacketDigest: string; certifiedAt: string; certifiedBy: string; }
export interface RawGameSampleEnvelope<TRawState = unknown> { gameRunId: string; sourceId: string; fence: number; controlOwnerType: GameControlOwnerType | null; bridgeVersion: string; bridgeDigest: string; rawSchemaVersion: string; relaySequence: number; sourceObservationSequence: number; observedAtAuthorityMs: number; rawState: TRawState; rawStateDigest: string; appliedControls?: Record<string, number | boolean>; appliedControlsDigest?: string; appliedDecision?: AppliedDecisionCorrelation; rawEnvelopeDigest: string; }
export interface GameObservation<TGameState = unknown> { gameRunId: string; sourceId: string; fence: number; controlOwnerType: GameControlOwnerType | null; runtimeProvenanceDigest: string; evidenceWindowContextDigest: string | null; observationSchemaVersion: string; sequence: number; sourceObservationSequence: number; sourceObservationDigest: string; observedAtAuthorityMs: number; lifecycle: "loading" | "menu" | "countdown" | "playing" | "paused" | "crashed" | "game_over" | "completed" | "stopped"; player?: { position?: { x: number; y: number; z: number }; velocity?: { x: number; y: number; z: number }; speed?: number; heading?: number; health?: number; score?: number; }; progression?: { distance?: number; checkpoint?: number; level?: number; remainingTimeMs?: number; }; entities?: Array<{ id: string; kind: string; relativePosition?: { x: number; y: number; z: number }; relativeVelocity?: { x: number; y: number; z: number }; }>; gameState: TGameState; appliedControls?: Record<string, number | boolean>; appliedDecision?: AppliedDecisionCorrelation; }
export interface GameEventDraft<TPayload = unknown> { type: string; payload: TPayload; }
export interface GameEvent<TPayload = unknown> { eventId: string; eventDigest: string; gameRunId: string; sourceId: string; fence: number; controlOwnerType: GameControlOwnerType | null; evidenceWindowContextDigest: string | null; eventSchemaVersion: string; type: string; eventIndex: number; sourceObservationSequence: number; sourceObservationDigest: string; occurredAtAuthorityMs: number; payload: TPayload; }
export interface GameEventRecord<TPayload = unknown> extends GameEvent<TPayload> { acceptedAtAuthorityMs: number; authorityClockDomainId: "redis-time-ms"; recordDigest: string; }
export interface AgentGameDirective<TPolicy = unknown, TRecoveryPolicy = unknown> { gameRunId: string; leaseId: string; fence: number; directiveId: string; directiveDigest: string; goal: string; strategyFamily: string; gameplayPolicyId: string; gameplayPolicyVersion: number; gameplayPolicyDigest: string; policySnapshot: TPolicy; recoveryPolicy: TRecoveryPolicy; memoryProvenanceIds: string[]; issuedAtAgentMonotonicMs: number; validForMs: number; agentClockDomainId: string; }
export type GameControlCommand = { kind: "digital"; controlId: string; pressed: boolean; } | { kind: "analog"; controlId: string; value: number; } | { kind: "pointer"; controlId: string; coordinateSpace: "game-normalized"; x: number; y: number; button?: "primary" | "secondary" | "middle"; phase: "move" | "press" | "release"; };
export interface GameControlIntent { gameRunId: string; leaseId: string; fence: number; directiveId: string; decisionId: string; semanticIntentDigest: string; observationSequence: number; decidedAtAgentMonotonicMs: number; maximumAgeMs: number; agentClockDomainId: string; commands: GameControlCommand[]; reasonCode: "pursue_objective" | "avoid_hazard" | "recover" | "lifecycle" | "stop"; }
export interface NormalizedGameControls { controlSchemaVersion: string; commands: GameControlCommand[]; maximumHoldMs: number; mappedControlsDigest: string; }
export interface AppliedDecisionCorrelation { leaseId: string; fence: number; ownerType: GameControlOwnerType; directiveId: string; decisionId: string; semanticIntentDigest: string; mappedControlsDigest: string; appliedControlsDigest: string; }
export interface AppliedControlSnapshot { gameRunId: string; leaseId: string | null; ownerType: GameControlOwnerType | null; fence: number; controlSchemaVersion: string; controls: Record<string, number | boolean>; appliedControlsDigest: string; decision: AppliedDecisionCorrelation | null; authorityOwned: boolean; physicsFrameSequence: number; committedAtPageMonotonicMs: number; pageClockDomainId: string; }
export interface BridgeObservationSample<TRawObservation = unknown> { rawState: TRawObservation; appliedControlSnapshot: AppliedControlSnapshot; }
export interface GameProgressVerdict { verdictId: string; verdictDigest: string; gameRunId: string; sourceId: string; fence: number; controlOwnerType: GameControlOwnerType | null; evidenceWindowContextDigest: string | null; progressSchemaVersion: string; fromSourceObservationSequence: number; toSourceObservationSequence: number; fromSourceObservationDigest: string; toSourceObservationDigest: string; evaluatedAtAuthorityMs: number; progressed: boolean; metrics: Record<string, number>; contributingDecisionIds: string[]; }
export interface GameControlReceipt { receiptId: string; gameRunId: string; leaseId: string; fence: number; ownerType: GameControlOwnerType; directiveId: string; decisionId: string; semanticIntentDigest: string; mappedControlsDigest: string; observationSequence: number; relaySequence: number; stageSequence: number; state: "accepted" | "enqueued" | "injected" | "reflected" | "rejected"; sourceId: string; authorityClockDomainId: "redis-time-ms"; acceptedAtAuthorityMs?: number; enqueuedAtAuthorityMs?: number; injectedAtAuthorityMs?: number; reflectedAtAuthorityMs?: number; reflectedObservationSequence?: number; appliedControls?: Record<string, number | boolean>; appliedControlsDigest?: string; rejectionCode?: "expired" | "out_of_order" | "authority_changed" | "bridge_unavailable" | "application_failed" | "reflection_timeout"; }
export interface GameControlReleaseRequest { releaseId: string; releaseDigest: string; gameRunId: string; leaseId: string; fence: number; directiveId: string; observationSequence: number; neutralSemanticIntentDigest: string; neutralMappedControlsDigest: string; }
export interface GameControlReleaseReceipt { receiptId: string; releaseId: string; releaseDigest: string; gameRunId: string; leaseId: string; ownerType: GameControlOwnerType; fence: number; directiveId: string; observationSequence: number; neutralSemanticIntentDigest: string; neutralMappedControlsDigest: string; relaySequence: number; stageSequence: number; state: "accepted" | "enqueued" | "injected" | "reflected" | "rejected"; sourceId: string; authorityClockDomainId: "redis-time-ms"; acceptedAtAuthorityMs?: number; enqueuedAtAuthorityMs?: number; injectedAtAuthorityMs?: number; reflectedAtAuthorityMs?: number; reflectedObservationSequence?: number; neutralAppliedControlsDigest?: string; neutralSnapshotDigest?: string; rejectionCode?: "out_of_order" | "authority_changed" | "bridge_unavailable" | "application_failed" | "neutral_not_observed"; }
export type GameplayReceipt = GameControlReceipt | GameControlReleaseReceipt;
export interface GameRuntimeCapabilities { bridgeId: string; bridgeVersion: string; bridgeDigest: string; observationSchemaVersion: string; eventSchemaVersion: string; progressSchemaVersion: string; controlSchemaVersion: string; supportedLifecycleCommands: Array<"start" | "pause" | "resume" | "restart">; controls: GameControlDescriptor[]; commandSemantics: "complete_snapshot" | "partial_events"; nativeFenceEnforcement: boolean; appliedControls: boolean; maximumIntentAgeMs: number; maximumHoldMs: number; maximumSilenceMs: number; }
export type GameLifecycleCommandResult = { status: "applied"; transitionId: string; requestDigest: string; command: "start" | "pause" | "resume" | "restart"; lifecycleRevision: number; runtimeRevision: number; certificationFixtureRevision?: number; completedAtPageMonotonicMs: number; pageClockDomainId: string; resultDigest: string; } | { status: "unsupported"; transitionId: string; requestDigest: string; command: "start" | "pause" | "resume" | "restart"; lifecycleRevision: number; runtimeRevision: number; certificationFixtureRevision?: number; resultDigest: string; } | { status: "rejected"; transitionId: string; requestDigest: string; command: "start" | "pause" | "resume" | "restart"; code: "wrong_run" | "stale_fence" | "inactive_authority" | "application_failed"; lifecycleRevision: number; runtimeRevision: number; certificationFixtureRevision?: number; resultDigest: string; };
export interface PageAuthorityCommitResult { transitionId: string; requestDigest: string; pageAuthorityRevision: number; pageAuthoritySnapshotDigest: string; completedAtPageMonotonicMs: number; pageClockDomainId: string; resultDigest: string; }
export interface PageControlReleaseResult { transitionId: string; requestDigest: string; pageAuthorityRevision: number; snapshot: AppliedControlSnapshot; completedAtPageMonotonicMs: number; pageClockDomainId: string; resultDigest: string; }
export interface Drive555InitialFixtureConfig { schemaVersion: "555drive.initial-fixture.v1"; fixtureId: "straight_start_1331_v1"; trackSeed: 1331; playerX: 0; playerZ: 2000; playerVelocityX: 0; playerVelocityZ: 0; fixtureDigest: string; }
export interface Drive555RecoveryPolicy { schemaVersion: "555drive.recovery.v1"; stallWindowMs: 4000; maximumPositionRange: 10; maximumAttempts: 1; action: "restart"; progressDeadlineMs: 5000; minimumForwardDelta: 1000; }
