import { canonicalJson, digestWithout, sha256Canonical } from "./canonical.js";
import type { AgentGameDirective, GameAdapterManifest, GameControlCommand, GameControlDescriptor, GameControlIntent, GameEvent, GameEventDraft, GameObservation, GameProgressVerdict, NormalizedGameControls } from "./contracts.js";

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const fail = (message: string): never => { throw new TypeError(message); };
const string = (value: unknown, field: string): string => typeof value === "string" && value.length > 0 ? value : fail(`${field} must be a non-empty string`);
const number = (value: unknown, field: string, integer = false): number => typeof value === "number" && Number.isFinite(value) && (!integer || Number.isInteger(value)) ? value : fail(`${field} must be a ${integer ? "finite integer" : "finite number"}`);
const closed = (value: Record<string, unknown>, keys: readonly string[], label: string): void => { for (const key of Object.keys(value)) if (!keys.includes(key)) fail(`${label} has unknown field ${key}`); };
const digest = (value: unknown, field: string): string => { const result = string(value, field); return /^[a-f0-9]{64}$/.test(result) ? result : fail(`${field} must be lowercase SHA-256 hex`); };

export const DRIVE555_V0_MANIFEST: GameAdapterManifest = {
  gameId: "555drive", adapterVersion: "1.0.0", observationSchemaVersion: "555drive.observation.v1", eventSchemaVersion: "555drive.events.v1", progressSchemaVersion: "555drive.progress.v1", controlSchemaVersion: "555drive.controls.v1", controllerFamilies: ["racing_line"], supportedLifecycleCommands: ["start", "restart"],
  observations: { stateSchemaId: "555drive.state.v1", featureIds: ["lifecycle", "frame", "trackSeed", "player.x", "player.z", "player.velocityX", "player.velocityZ", "checkpoint", "remainingTimeMs", "score", "collisionSequence", "lastCollision", "hazards", "appliedControls", "appliedDecision"], appliedControls: true, minimumHz: 10, maximumGapMs: 300 },
  controls: { descriptors: [{ id: "accelerate", kind: "analog", minimum: 0, maximum: 1, neutral: 0 }, { id: "brake", kind: "analog", minimum: 0, maximum: 1, neutral: 0 }, { id: "steer", kind: "analog", minimum: -1, maximum: 1, neutral: 0 }], commandSemantics: "complete_snapshot", maximumIntentAgeMs: 250, maximumHoldMs: 300, maximumSilenceMs: 500 },
  evidence: { stateProgression: true, visualProgression: true, deterministicReplay: true },
};

function descriptor(value: unknown): GameControlDescriptor {
  if (!isRecord(value)) return fail("control descriptor must be an object");
  const id = string(value.id, "descriptor.id");
  if (value.kind === "digital") { closed(value, ["id", "kind", "supportsHold", "neutral"], "digital descriptor"); if (typeof value.supportsHold !== "boolean" || value.neutral !== false) fail("invalid digital descriptor"); return { id, kind: "digital", supportsHold: value.supportsHold as boolean, neutral: false }; }
  if (value.kind === "analog") { closed(value, ["id", "kind", "minimum", "maximum", "neutral"], "analog descriptor"); const minimum = number(value.minimum, "minimum"); const maximum = number(value.maximum, "maximum"); const neutral = number(value.neutral, "neutral"); if (minimum > maximum || neutral < minimum || neutral > maximum) fail("invalid analog bounds"); return { id, kind: "analog", minimum, maximum, neutral }; }
  if (value.kind === "pointer") { closed(value, ["id", "kind", "coordinateSpace", "buttons", "supportsMove", "supportsHold"], "pointer descriptor"); if (value.coordinateSpace !== "game-normalized" || !Array.isArray(value.buttons) || !value.buttons.every((button) => button === "primary" || button === "secondary" || button === "middle") || typeof value.supportsMove !== "boolean" || typeof value.supportsHold !== "boolean") fail("invalid pointer descriptor"); return { id, kind: "pointer", coordinateSpace: "game-normalized", buttons: [...value.buttons as unknown[]] as Array<"primary" | "secondary" | "middle">, supportsMove: value.supportsMove as boolean, supportsHold: value.supportsHold as boolean }; }
  return fail("unknown control descriptor kind");
}

export function validateManifest(value: unknown): GameAdapterManifest {
  if (!isRecord(value)) return fail("manifest must be an object");
  closed(value, ["gameId", "adapterVersion", "observationSchemaVersion", "eventSchemaVersion", "progressSchemaVersion", "controlSchemaVersion", "controllerFamilies", "supportedLifecycleCommands", "observations", "controls", "evidence"], "manifest");
  if (!Array.isArray(value.controllerFamilies) || !value.controllerFamilies.every((entry) => typeof entry === "string") || !Array.isArray(value.supportedLifecycleCommands) || !value.supportedLifecycleCommands.every((entry) => entry === "start" || entry === "pause" || entry === "resume" || entry === "restart") || !isRecord(value.observations) || !isRecord(value.controls) || !isRecord(value.evidence)) return fail("invalid manifest structure");
  closed(value.observations, ["stateSchemaId", "featureIds", "appliedControls", "minimumHz", "maximumGapMs"], "observations"); closed(value.controls, ["descriptors", "commandSemantics", "maximumIntentAgeMs", "maximumHoldMs", "maximumSilenceMs"], "controls"); closed(value.evidence, ["stateProgression", "visualProgression", "deterministicReplay"], "evidence");
  if (!Array.isArray(value.observations.featureIds) || !value.observations.featureIds.every((entry) => typeof entry === "string") || typeof value.observations.appliedControls !== "boolean" || !Array.isArray(value.controls.descriptors) || (value.controls.commandSemantics !== "complete_snapshot" && value.controls.commandSemantics !== "partial_events") || typeof value.evidence.stateProgression !== "boolean" || typeof value.evidence.visualProgression !== "boolean" || typeof value.evidence.deterministicReplay !== "boolean") return fail("invalid manifest fields");
  const descriptors = value.controls.descriptors.map(descriptor); if (new Set(descriptors.map((entry) => entry.id)).size !== descriptors.length) fail("duplicate control descriptor id");
  const maximumIntentAgeMs = number(value.controls.maximumIntentAgeMs, "maximumIntentAgeMs", true), maximumHoldMs = number(value.controls.maximumHoldMs, "maximumHoldMs", true), maximumSilenceMs = number(value.controls.maximumSilenceMs, "maximumSilenceMs", true); if (maximumIntentAgeMs < 0 || maximumHoldMs < 0 || maximumSilenceMs < 0) fail("control durations must be positive");
  return { gameId: string(value.gameId, "gameId"), adapterVersion: string(value.adapterVersion, "adapterVersion"), observationSchemaVersion: string(value.observationSchemaVersion, "observationSchemaVersion"), eventSchemaVersion: string(value.eventSchemaVersion, "eventSchemaVersion"), progressSchemaVersion: string(value.progressSchemaVersion, "progressSchemaVersion"), controlSchemaVersion: string(value.controlSchemaVersion, "controlSchemaVersion"), controllerFamilies: [...value.controllerFamilies] as string[], supportedLifecycleCommands: [...value.supportedLifecycleCommands] as GameAdapterManifest["supportedLifecycleCommands"], observations: { stateSchemaId: string(value.observations.stateSchemaId, "stateSchemaId"), featureIds: [...value.observations.featureIds] as string[], appliedControls: value.observations.appliedControls as boolean, minimumHz: number(value.observations.minimumHz, "minimumHz"), maximumGapMs: number(value.observations.maximumGapMs, "maximumGapMs", true) }, controls: { descriptors, commandSemantics: value.controls.commandSemantics as "complete_snapshot" | "partial_events", maximumIntentAgeMs, maximumHoldMs, maximumSilenceMs }, evidence: { stateProgression: value.evidence.stateProgression as boolean, visualProgression: value.evidence.visualProgression as boolean, deterministicReplay: value.evidence.deterministicReplay as boolean } };
}

export function validateDirective<TPolicy>(value: unknown, policyValidator: (value: unknown) => TPolicy): AgentGameDirective<TPolicy> {
  if (!isRecord(value)) return fail("directive must be an object");
  const keys = ["gameRunId", "leaseId", "fence", "directiveId", "directiveDigest", "goal", "strategyFamily", "gameplayPolicyId", "gameplayPolicyVersion", "gameplayPolicyDigest", "policySnapshot", "recoveryPolicy", "memoryProvenanceIds", "issuedAtAgentMonotonicMs", "validForMs", "agentClockDomainId"]; closed(value, keys, "directive");
  const recoveryPolicy = value.recoveryPolicy; if (!Array.isArray(value.memoryProvenanceIds) || !value.memoryProvenanceIds.every((entry) => typeof entry === "string")) fail("directive requires string memory provenance ids"); if (!isRecord(recoveryPolicy)) fail("directive requires a typed recovery policy");
  const typedRecoveryPolicy = recoveryPolicy as Record<string, unknown>; const policySnapshot = policyValidator(value.policySnapshot); const recoverySchemaVersion = string(typedRecoveryPolicy.schemaVersion, "recoveryPolicy.schemaVersion"); if (recoverySchemaVersion !== "555drive.recovery.v1" || Object.keys(typedRecoveryPolicy).sort().join(",") !== "action,maximumAttempts,maximumPositionRange,minimumForwardDelta,progressDeadlineMs,schemaVersion,stallWindowMs" || typedRecoveryPolicy.stallWindowMs !== 4000 || typedRecoveryPolicy.maximumPositionRange !== 10 || typedRecoveryPolicy.maximumAttempts !== 1 || typedRecoveryPolicy.action !== "restart" || typedRecoveryPolicy.progressDeadlineMs !== 5000 || typedRecoveryPolicy.minimumForwardDelta !== 1000) fail("invalid typed recovery policy"); const policySchemaVersion = isRecord(value.policySnapshot) && typeof value.policySnapshot.schemaVersion === "string" ? value.policySnapshot.schemaVersion : undefined; if (!policySchemaVersion) fail("policySnapshot.schemaVersion is required");
  const policyDigest = digest(value.gameplayPolicyDigest, "gameplayPolicyDigest"); if (policyDigest !== sha256Canonical({ policySnapshot: value.policySnapshot, policySchemaVersion, recoveryPolicy: value.recoveryPolicy, recoveryPolicySchemaVersion: recoverySchemaVersion })) fail("gameplay policy digest mismatch");
  const directiveDigest = digest(value.directiveDigest, "directiveDigest"); if (directiveDigest !== digestWithout(value, ["directiveDigest"])) fail("directive digest mismatch");
  return { gameRunId: string(value.gameRunId, "gameRunId"), leaseId: string(value.leaseId, "leaseId"), fence: number(value.fence, "fence", true), directiveId: string(value.directiveId, "directiveId"), directiveDigest, goal: string(value.goal, "goal"), strategyFamily: string(value.strategyFamily, "strategyFamily"), gameplayPolicyId: string(value.gameplayPolicyId, "gameplayPolicyId"), gameplayPolicyVersion: number(value.gameplayPolicyVersion, "gameplayPolicyVersion", true), gameplayPolicyDigest: policyDigest, policySnapshot, recoveryPolicy, memoryProvenanceIds: [...value.memoryProvenanceIds as unknown[]] as string[], issuedAtAgentMonotonicMs: number(value.issuedAtAgentMonotonicMs, "issuedAtAgentMonotonicMs", true), validForMs: number(value.validForMs, "validForMs", true), agentClockDomainId: string(value.agentClockDomainId, "agentClockDomainId") };
}

function validateCommand(value: unknown, manifest: GameAdapterManifest): GameControlCommand {
  if (!isRecord(value)) return fail("command must be an object"); const controlId = string(value.controlId, "controlId"); const descriptorValue = manifest.controls.descriptors.find((entry) => entry.id === controlId); if (!descriptorValue || descriptorValue.kind !== value.kind) return fail("unknown or mismatched control");
  if (value.kind === "digital") { closed(value, ["kind", "controlId", "pressed"], "digital command"); if (typeof value.pressed !== "boolean") fail("pressed must be boolean"); return { kind: "digital", controlId, pressed: value.pressed as boolean }; }
  if (value.kind === "analog") { closed(value, ["kind", "controlId", "value"], "analog command"); if (descriptorValue.kind !== "analog") return fail("mismatched analog"); const mapped = number(value.value, "value"); if (mapped < descriptorValue.minimum || mapped > descriptorValue.maximum) fail("analog value outside descriptor bounds"); return { kind: "analog", controlId, value: mapped }; }
  if (value.kind === "pointer") { closed(value, ["kind", "controlId", "coordinateSpace", "x", "y", "button", "phase"], "pointer command"); if (descriptorValue.kind !== "pointer" || value.coordinateSpace !== "game-normalized" || (value.phase !== "move" && value.phase !== "press" && value.phase !== "release") || (value.button !== undefined && !descriptorValue.buttons.includes(value.button as "primary"))) fail("invalid pointer command"); const x = number(value.x, "x"), y = number(value.y, "y"); if (x < 0 || x > 1 || y < 0 || y > 1) fail("pointer coordinates must be normalized"); return { kind: "pointer", controlId, coordinateSpace: "game-normalized", x, y, ...(value.button === undefined ? {} : { button: value.button as "primary" | "secondary" | "middle" }), phase: value.phase as "move" | "press" | "release" }; }
  return fail("unknown command kind");
}

export function validateControlIntent(value: unknown, manifestInput: GameAdapterManifest): GameControlIntent {
  const manifest = validateManifest(manifestInput); if (!isRecord(value)) return fail("intent must be an object");
  closed(value, ["gameRunId", "leaseId", "fence", "directiveId", "decisionId", "semanticIntentDigest", "observationSequence", "decidedAtAgentMonotonicMs", "maximumAgeMs", "agentClockDomainId", "commands", "reasonCode"], "intent");
  if (!Array.isArray(value.commands)) return fail("intent commands must be an array"); const maximumAgeMs = number(value.maximumAgeMs, "maximumAgeMs", true); if (maximumAgeMs < 0) fail("maximumAgeMs must be positive"); const reasonCode = value.reasonCode; if (reasonCode !== "pursue_objective" && reasonCode !== "avoid_hazard" && reasonCode !== "recover" && reasonCode !== "lifecycle" && reasonCode !== "stop") fail("invalid intent reason code");
  const semanticIntentDigest = digest(value.semanticIntentDigest, "semanticIntentDigest"); if (semanticIntentDigest !== digestWithout(value, ["semanticIntentDigest"])) fail("semantic intent digest mismatch"); const commands = value.commands.map((entry) => validateCommand(entry, manifest)); if (new Set(commands.map((entry) => entry.controlId)).size !== commands.length) fail("duplicate control command");
  return { gameRunId: string(value.gameRunId, "gameRunId"), leaseId: string(value.leaseId, "leaseId"), fence: number(value.fence, "fence", true), directiveId: string(value.directiveId, "directiveId"), decisionId: string(value.decisionId, "decisionId"), semanticIntentDigest, observationSequence: number(value.observationSequence, "observationSequence", true), decidedAtAgentMonotonicMs: number(value.decidedAtAgentMonotonicMs, "decidedAtAgentMonotonicMs", true), maximumAgeMs, agentClockDomainId: string(value.agentClockDomainId, "agentClockDomainId"), commands, reasonCode: reasonCode as GameControlIntent["reasonCode"] };
}

export function mapControlIntent(value: GameControlIntent, manifestInput: GameAdapterManifest): NormalizedGameControls {
  const manifest = validateManifest(manifestInput); const intent = validateControlIntent(value, manifest); const commands = intent.commands.map((entry) => validateCommand(entry, manifest)); if (new Set(commands.map((entry) => entry.controlId)).size !== commands.length) fail("duplicate control command");
  if (manifest.controls.commandSemantics === "complete_snapshot" && manifest.controls.descriptors.some((entry) => entry.kind === "pointer")) fail("complete snapshots forbid pointers");
  const byId = new Map(commands.map((entry) => [entry.controlId, entry])); const normalized = manifest.controls.descriptors.flatMap((entry) => { const found = byId.get(entry.id); if (found) return [found]; if (manifest.controls.commandSemantics === "partial_events") return []; return entry.kind === "analog" ? [{ kind: "analog" as const, controlId: entry.id, value: entry.neutral }] : [{ kind: "digital" as const, controlId: entry.id, pressed: false }]; });
  const maximumHoldMs = Math.min(manifest.controls.maximumHoldMs, manifest.controls.maximumSilenceMs, Math.min(intent.maximumAgeMs, manifest.controls.maximumIntentAgeMs)); const base = { controlSchemaVersion: manifest.controlSchemaVersion, commands: normalized, maximumHoldMs };
  return { ...base, mappedControlsDigest: sha256Canonical(base) };
}

export function createAttributedGameEventDraft(type: string, payload: unknown): GameEventDraft { return { type: string(type, "event type"), payload }; }
export function finalizeGameEvents(observation: GameObservation, eventSchemaVersion: string, drafts: readonly GameEventDraft[]): GameEvent[] {
  const validObservation = validateObservation(observation); const sourceId = validObservation.sourceId, sourceObservationDigest = validObservation.sourceObservationDigest;
  return [...drafts].map((draft) => ({ type: string(draft.type, "event type"), payload: draft.payload })).sort((left, right) => left.type.localeCompare(right.type) || canonicalPayload(left.payload).localeCompare(canonicalPayload(right.payload))).map((draft, eventIndex) => { const stable = { gameRunId: validObservation.gameRunId, sourceId, fence: validObservation.fence, controlOwnerType: validObservation.controlOwnerType, evidenceWindowContextDigest: validObservation.evidenceWindowContextDigest, eventSchemaVersion: string(eventSchemaVersion, "eventSchemaVersion"), type: draft.type, sourceObservationSequence: validObservation.sourceObservationSequence, sourceObservationDigest, eventIndex }; const eventId = sha256Canonical(stable); const result = { ...stable, eventId, occurredAtAuthorityMs: validObservation.observedAtAuthorityMs, payload: draft.payload }; return validateGameEvent({ ...result, eventDigest: sha256Canonical(result) }); });
}
const canonicalPayload = (payload: unknown): string => canonicalJson(payload);

export function createGameProgressVerdict(input: Omit<GameProgressVerdict, "verdictId" | "verdictDigest">): GameProgressVerdict { const stable = { gameRunId: input.gameRunId, sourceId: input.sourceId, fence: input.fence, controlOwnerType: input.controlOwnerType, evidenceWindowContextDigest: input.evidenceWindowContextDigest, progressSchemaVersion: input.progressSchemaVersion, fromSourceObservationSequence: input.fromSourceObservationSequence, toSourceObservationSequence: input.toSourceObservationSequence, fromSourceObservationDigest: input.fromSourceObservationDigest, toSourceObservationDigest: input.toSourceObservationDigest }; const verdictId = sha256Canonical(stable); const verdict = { ...input, verdictId }; return { ...verdict, verdictDigest: sha256Canonical(verdict) }; }

export function validateAppliedDecisionCorrelation(value: unknown): import("./contracts.js").AppliedDecisionCorrelation { if (!isRecord(value)) return fail("applied decision must be an object"); closed(value, ["leaseId", "fence", "ownerType", "directiveId", "decisionId", "semanticIntentDigest", "mappedControlsDigest", "appliedControlsDigest"], "applied decision"); if (value.ownerType !== "agent" && value.ownerType !== "certification_harness") fail("invalid applied decision owner"); return { leaseId: string(value.leaseId, "leaseId"), fence: number(value.fence, "fence", true), ownerType: value.ownerType as import("./contracts.js").GameControlOwnerType, directiveId: string(value.directiveId, "directiveId"), decisionId: string(value.decisionId, "decisionId"), semanticIntentDigest: digest(value.semanticIntentDigest, "semanticIntentDigest"), mappedControlsDigest: digest(value.mappedControlsDigest, "mappedControlsDigest"), appliedControlsDigest: digest(value.appliedControlsDigest, "appliedControlsDigest") }; }
export function validateObservation(value: unknown, expected?: Pick<GameObservation, "gameRunId" | "sourceId" | "fence" | "controlOwnerType" | "sourceObservationSequence" | "sourceObservationDigest" | "observedAtAuthorityMs">): GameObservation { if (!isRecord(value)) return fail("observation must be an object"); for (const key of ["gameRunId", "sourceId", "fence", "controlOwnerType", "runtimeProvenanceDigest", "evidenceWindowContextDigest", "observationSchemaVersion", "sequence", "sourceObservationSequence", "sourceObservationDigest", "observedAtAuthorityMs", "lifecycle", "gameState"]) if (!(key in value)) fail(`missing observation field ${key}`); const owner = value.controlOwnerType; if (owner !== null && owner !== "agent" && owner !== "certification_harness") fail("invalid observation owner"); const sourceSequence = number(value.sourceObservationSequence, "sourceObservationSequence", true); if (number(value.sequence, "sequence", true) !== sourceSequence) fail("observation sequence must equal source sequence"); const result = value as unknown as GameObservation; string(result.gameRunId, "gameRunId"); string(result.sourceId, "sourceId"); number(result.fence, "fence", true); digest(result.runtimeProvenanceDigest, "runtimeProvenanceDigest"); digest(result.sourceObservationDigest, "sourceObservationDigest"); number(result.observedAtAuthorityMs, "observedAtAuthorityMs", true); if (result.evidenceWindowContextDigest !== null) digest(result.evidenceWindowContextDigest, "evidenceWindowContextDigest"); if (result.appliedDecision) { const decision = validateAppliedDecisionCorrelation(result.appliedDecision); if (decision.ownerType !== owner || decision.fence !== result.fence) fail("applied decision authority mismatch"); } const authorityKeys = ["gameRunId", "sourceId", "fence", "controlOwnerType", "sourceObservationSequence", "sourceObservationDigest", "observedAtAuthorityMs"] as const; if (expected && authorityKeys.some((key) => result[key] !== expected[key])) fail("observation authority tuple mismatch"); return result; }
export function validateGameEvent(value: unknown): GameEvent { if (!isRecord(value)) return fail("event must be an object"); const event = value as unknown as GameEvent; const stable = { gameRunId: string(event.gameRunId, "gameRunId"), sourceId: string(event.sourceId, "sourceId"), fence: number(event.fence, "fence", true), controlOwnerType: event.controlOwnerType, evidenceWindowContextDigest: event.evidenceWindowContextDigest, eventSchemaVersion: string(event.eventSchemaVersion, "eventSchemaVersion"), type: string(event.type, "type"), sourceObservationSequence: number(event.sourceObservationSequence, "sourceObservationSequence", true), sourceObservationDigest: digest(event.sourceObservationDigest, "sourceObservationDigest"), eventIndex: number(event.eventIndex, "eventIndex", true) }; if (event.controlOwnerType !== null && event.controlOwnerType !== "agent" && event.controlOwnerType !== "certification_harness") fail("invalid event owner"); if (event.evidenceWindowContextDigest !== null) digest(event.evidenceWindowContextDigest, "evidenceWindowContextDigest"); number(event.occurredAtAuthorityMs, "occurredAtAuthorityMs", true); if (event.eventId !== sha256Canonical(stable)) fail("event id mismatch"); if (event.eventDigest !== sha256Canonical({ ...stable, eventId: event.eventId, occurredAtAuthorityMs: event.occurredAtAuthorityMs, payload: event.payload })) fail("event digest mismatch"); return event; }
export function validateProgressVerdict(value: unknown): GameProgressVerdict { if (!isRecord(value)) return fail("verdict must be an object"); const verdict = value as unknown as GameProgressVerdict; const stable = { gameRunId: string(verdict.gameRunId, "gameRunId"), sourceId: string(verdict.sourceId, "sourceId"), fence: number(verdict.fence, "fence", true), controlOwnerType: verdict.controlOwnerType, evidenceWindowContextDigest: verdict.evidenceWindowContextDigest, progressSchemaVersion: string(verdict.progressSchemaVersion, "progressSchemaVersion"), fromSourceObservationSequence: number(verdict.fromSourceObservationSequence, "fromSourceObservationSequence", true), toSourceObservationSequence: number(verdict.toSourceObservationSequence, "toSourceObservationSequence", true), fromSourceObservationDigest: digest(verdict.fromSourceObservationDigest, "fromSourceObservationDigest"), toSourceObservationDigest: digest(verdict.toSourceObservationDigest, "toSourceObservationDigest") }; if (stable.toSourceObservationSequence <= stable.fromSourceObservationSequence || (verdict.controlOwnerType !== null && verdict.controlOwnerType !== "agent" && verdict.controlOwnerType !== "certification_harness")) fail("invalid verdict authority tuple"); if (verdict.evidenceWindowContextDigest !== null) digest(verdict.evidenceWindowContextDigest, "evidenceWindowContextDigest"); number(verdict.evaluatedAtAuthorityMs, "evaluatedAtAuthorityMs", true); if (!Object.values(verdict.metrics).every((entry) => typeof entry === "number" && Number.isFinite(entry)) || !verdict.contributingDecisionIds.every((entry) => typeof entry === "string")) fail("invalid verdict values"); if (verdict.verdictId !== sha256Canonical(stable)) fail("verdict id mismatch"); const withoutDigest = { ...verdict }; delete (withoutDigest as Partial<GameProgressVerdict>).verdictDigest; if (verdict.verdictDigest !== sha256Canonical(withoutDigest)) fail("verdict digest mismatch"); return verdict; }
